[theme]
primaryColor = "#1EB3B2"
backgroundColor = "#000000"
secondaryBackgroundColor = "#192E41"
textColor = "#7FF9C6"
font = "sans serif"

[server]
maxUploadSize = 2000  # Aumenta o limite para 2000MB (2GB)